# Generated by Django 4.1.3 on 2022-11-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authoor',
            new_name='author',
        ),
    ]
